name: Release Docker image into ACR

on:
  push:
    branches: [ "test" ]

jobs:

  Release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build -t pacman-app .
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USER }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_SERVER }}
      
    - name: Tag Docker image
      run: docker tag pacman-app ${{ secrets.ACR_SERVER }}/pacman-app
    
    - name: Push Docker image into ACR
      run: docker push ${{ secrets.ACR_SERVER }}/pacman-app

  Deploy:
  
    needs: Release
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1.1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: ${{ secrets.AZ_CREDS }}
        # Resource Group Name
        resource-group:  ${{ secrets.AKS_RG }}
        # AKS Cluster Name
        cluster-name:  ${{ secrets.AKS_NAME }}
    
    - name: Restart Deployment
      run: kubectl -n pacman rollout restart deployment pacman
