name: Release Docker image into ACR

on:
  push:
    branches: [ master ]

jobs:

  Release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USER }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_SERVER }}
        
    - name: Build the Docker image
      run: docker build -t pacman-app .
      
    - name: Tag Docker image
      run: docker tag pacman-app ${{ secrets.ACR_SERVER }}/pacman-app
    
    - name: Push Docker image into ACR
      run: docker push ${{ secrets.ACR_SERVER }}/pacman-app
    
  Deploy:
  
    needs: Release
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1.3
      with:
        namespace: pacman
        # Path to the manifest files which will be used for deployment.
        manifests: k8s/
        images: ${{ secrets.ACR_SERVER }}/pacman-app:latest
